[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.check-manifest]
ignore = ["*/__pycache__"]
[project]
name = "youtube_downloader"
version = "1.0.0"
